import os
import sys
import subprocess
import shutil
from typing import Optional, Dict, Any


class RVCPipelineError(Exception):
    """Exception class for RVC Pipeline errors."""
    pass


class RVCPostProcessor:
    """
    Retrieval-based Voice Conversion (RVC) post-processor for XTTS Studio.

    This class handles the voice conversion layer, taking the raw base voice
    generated by XTTS v2 and passing it through RVC to significantly enhance
    the naturalness, timber match, emotional texture, and clarity.
    """

    def __init__(self, models_dir: str = "models/rvc", device: str = "cuda:0"):
        self.models_dir = os.path.abspath(models_dir)
        # rvc-python ожидает вид "cuda:0" / "cpu:0"; "cpu" без суффикса тоже
        # встречается в наших вызовах — нормализуем.
        self.device = self._normalize_device(device)
        os.makedirs(self.models_dir, exist_ok=True)

    @staticmethod
    def _normalize_device(device: str) -> str:
        d = (device or "cpu:0").strip().lower()
        if d in ("cpu", "cpu:0", "cpu0"):
            return "cpu:0"
        if d in ("cuda", "gpu"):
            return "cuda:0"
        if d.startswith("cuda") and ":" not in d:
            # "cuda0" → "cuda:0"
            rest = d[4:]
            return f"cuda:{rest or '0'}"
        return device

    def run_inference_via_lib(
        self,
        input_path: str,
        output_path: str,
        model_name: str,
        index_rate: float = 0.75,
        pitch_shift: int = 0,
        f0_method: str = "rmvpe",
    ) -> str:
        """
        Runs RVC voice conversion programmatically using the `rvc-python` library.
        Returns the path to the transformed output WAV.

        API rvc-python 0.1.5 (daswer123/rvc-python):
          - параметры задаются через set_params(f0up_key=..., f0method=..., ...)
          - infer_file(input_path, output_path) принимает ТОЛЬКО 2 аргумента
          - index передаётся в load_model(..., index_path=...)
        """
        try:
            # We import rvc-python on demand (lazy loading!)
            from rvc_python.infer import RVCInference
        except ImportError:
            raise RVCPipelineError(
                "RVC library 'rvc-python' is not installed. "
                "Please run 'pip install rvc-python' or check your python environment."
            )

        model_path = os.path.join(self.models_dir, f"{model_name}.pth")
        index_path = os.path.join(self.models_dir, f"{model_name}.index")

        if not os.path.exists(model_path):
            raise RVCPipelineError(f"RVC model checkpoint not found: {model_path}")

        # Note: Index file is optional but highly recommended for better similarity
        actual_index_path = index_path if os.path.exists(index_path) else ""

        try:
            # Initialize RVC Inference
            rvc_engine = RVCInference(device=self.device)

            # index_path — в load_model, НЕ в infer_file
            rvc_engine.load_model(
                model_path,
                version="v2",
                index_path=actual_index_path,
            )

            # Параметры — через set_params (имена как в rvc-python: f0up_key / f0method)
            rvc_engine.set_params(
                f0up_key=int(pitch_shift),
                f0method=str(f0_method or "rmvpe"),
                index_rate=float(index_rate),
                # разумные дефолты библиотеки, явно фиксируем для стабильности
                filter_radius=3,
                resample_sr=0,
                rms_mix_rate=0.25,
                protect=0.33,
            )

            # infer_file принимает только input_path, output_path
            rvc_engine.infer_file(input_path, output_path)

            if not os.path.isfile(output_path):
                raise RVCPipelineError(
                    f"RVC finished without producing output file: {output_path}"
                )
            return output_path
        except RVCPipelineError:
            raise
        except TypeError as e:
            # Подсказка, если вдруг стоит другая версия rvc-python с иным API
            raise RVCPipelineError(
                f"RVC library inference failed (API mismatch with rvc-python): {e}. "
                f"Expected set_params(f0up_key=..., f0method=...) + "
                f"infer_file(input_path, output_path)."
            )
        except Exception as e:
            raise RVCPipelineError(f"RVC library inference failed: {e}")

    def run_inference_via_cli(
        self,
        input_path: str,
        output_path: str,
        model_name: str,
        pitch_shift: int = 0,
        f0_method: str = "rmvpe",
        index_rate: float = 0.75,
        rvc_cli_dir: str = "tools/RVC_CLI",
    ) -> str:
        """
        Runs RVC conversion via a CLI subprocess call.
        Ideal for standalone executable environments or pre-built RVC packages.
        """
        model_path = os.path.join(self.models_dir, f"{model_name}.pth")
        index_path = os.path.join(self.models_dir, f"{model_name}.index")

        if not os.path.exists(model_path):
            raise RVCPipelineError(f"RVC model not found: {model_path}")

        # Build command based on RVC CLI layout
        # (Standard layout uses a python launcher or shell script)
        cli_script = os.path.join(rvc_cli_dir, "rvc.py")
        if not os.path.exists(cli_script):
            cli_script = "rvc"  # fallback to global command if path not set

        # Check if RVC script/command is available
        if not shutil.which("python") and not shutil.which("python3"):
            raise RVCPipelineError("Python is not found in PATH to call RVC CLI.")

        cmd = [
            "python", cli_script, "infer",
            "--input_path", input_path,
            "--output_path", output_path,
            "--pth_path", model_path,
            "--f0up_key", str(pitch_shift),
            "--f0method", f0_method,
            "--index_rate", str(index_rate),
        ]

        if os.path.exists(index_path):
            cmd.extend(["--index_path", index_path])

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True,
                encoding="utf-8"
            )
            return output_path
        except subprocess.CalledProcessError as e:
            raise RVCPipelineError(
                f"RVC CLI command failed with exit code {e.returncode}.\n"
                f"STDOUT: {e.stdout}\nSTDERR: {e.stderr}"
            )
        except Exception as e:
            raise RVCPipelineError(f"Failed to execute RVC CLI: {e}")


class XTTSWithRVCPipeline:
    """
    A unified orchestration class that chains XTTS v2 generation with RVC voice conversion.
    """

    def __init__(self, rvc_processor: RVCPostProcessor):
        self.rvc_processor = rvc_processor

    def generate_and_enhance(
        self,
        text: str,
        language: str,
        speaker_wav: str,
        output_path: str,
        xtts_generator_func,  # callback to generate intermediate audio using XTTS
        rvc_model: Optional[str] = None,
        rvc_settings: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Executes the dual-layer pipeline:
        1. Generates pristine base audio using XTTS v2.
        2. Post-processes the audio using RVC to enhance realism and similarity.
        """
        # If RVC model is not requested, return raw XTTS audio
        if not rvc_model:
            return xtts_generator_func(text, language, speaker_wav, output_path)

        # 1. Create a temporary path for the raw XTTS generation
        base_dir, ext = os.path.splitext(output_path)
        temp_xtts_output = f"{base_dir}_temp_xtts.wav"

        try:
            xtts_generator_func(text, language, speaker_wav, temp_xtts_output)

            if not os.path.exists(temp_xtts_output):
                raise RVCPipelineError("XTTS base generation failed to produce output file.")

            # 2. Apply RVC Voice Conversion
            # Default settings
            settings = {
                "index_rate": 0.75,
                "pitch_shift": 0,
                "f0_method": "rmvpe"
            }
            if rvc_settings:
                settings.update(rvc_settings)

            # Convert
            self.rvc_processor.run_inference_via_lib(
                input_path=temp_xtts_output,
                output_path=output_path,
                model_name=rvc_model,
                index_rate=settings["index_rate"],
                pitch_shift=settings["pitch_shift"],
                f0_method=settings["f0_method"]
            )

            return output_path

        finally:
            # Clean up intermediate file
            if os.path.exists(temp_xtts_output):
                try:
                    os.remove(temp_xtts_output)
                except Exception:
                    pass
